// <auto-generated />
using System;
using FailurePredictionSystemBack.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FailurePredictionSystemBack.Persistence.Migrations
{
    [DbContext(typeof(FailureSystemDbContext))]
    [Migration("20260518132207_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PredictionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("IsResolved");

                    b.HasIndex("PredictionId")
                        .IsUnique();

                    b.HasIndex("Severity");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentTokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hostname")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .IsUnique();

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Metric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<double>("DiskUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<double>("FreeDiskSpaceGb")
                        .HasColumnType("double precision");

                    b.Property<string>("Hostname")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PredictionStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<double>("RamUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("State")
                        .HasColumnType("integer");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("UptimeHours")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("PredictionStatus");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CriticalProbability")
                        .HasColumnType("double precision");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MetricId")
                        .HasColumnType("uuid");

                    b.Property<double>("NormalProbability")
                        .HasColumnType("double precision");

                    b.Property<int>("PredictedState")
                        .HasColumnType("integer");

                    b.Property<double>("WarningProbability")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("MetricId")
                        .IsUnique();

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Alert", b =>
                {
                    b.HasOne("FailurePredictionSystemBack.Core.Models.Equipment", "Equipment")
                        .WithMany("Alerts")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FailurePredictionSystemBack.Core.Models.Prediction", "Prediction")
                        .WithOne("Alert")
                        .HasForeignKey("FailurePredictionSystemBack.Core.Models.Alert", "PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Metric", b =>
                {
                    b.HasOne("FailurePredictionSystemBack.Core.Models.Equipment", "Equipment")
                        .WithMany("Metrics")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Prediction", b =>
                {
                    b.HasOne("FailurePredictionSystemBack.Core.Models.Equipment", "Equipment")
                        .WithMany("Predictions")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FailurePredictionSystemBack.Core.Models.Metric", "Metric")
                        .WithOne("Prediction")
                        .HasForeignKey("FailurePredictionSystemBack.Core.Models.Prediction", "MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Equipment", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Metrics");

                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Metric", b =>
                {
                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Prediction", b =>
                {
                    b.Navigation("Alert");
                });
#pragma warning restore 612, 618
        }
    }
}
