// <auto-generated />
using System;
using FailurePredictionSystemBack.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FailurePredictionSystemBack.Persistence.Migrations
{
    [DbContext(typeof(FailureSystemDbContext))]
    partial class FailureSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PredictionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("IsResolved");

                    b.HasIndex("PredictionId")
                        .IsUnique();

                    b.HasIndex("Severity");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentTokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Hostname")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.EquipmentNotificationSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEmailEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInAppEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("UserId");

                    b.HasIndex("EquipmentId", "UserId")
                        .IsUnique();

                    b.ToTable("EquipmentNotificationSubscriptions");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Metric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<double>("DiskUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<double>("FreeDiskSpaceGb")
                        .HasColumnType("double precision");

                    b.Property<string>("Hostname")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PredictionStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<double>("RamUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("State")
                        .HasColumnType("integer");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("UptimeHours")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("PredictionStatus");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlertId");

                    b.HasIndex("Channel");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsRead");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CriticalProbability")
                        .HasColumnType("double precision");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MetricId")
                        .HasColumnType("uuid");

                    b.Property<double>("NormalProbability")
                        .HasColumnType("double precision");

                    b.Property<int>("PredictedState")
                        .HasColumnType("integer");

                    b.Property<double>("WarningProbability")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("MetricId")
                        .IsUnique();

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Alert", b =>
                {
                    b.HasOne("FailurePredictionSystemBack.Core.Models.Equipment", "Equipment")
                        .WithMany("Alerts")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FailurePredictionSystemBack.Core.Models.Prediction", "Prediction")
                        .WithOne("Alert")
                        .HasForeignKey("FailurePredictionSystemBack.Core.Models.Alert", "PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Equipment", b =>
                {
                    b.HasOne("FailurePredictionSystemBack.Core.Models.User", "CreatedByUser")
                        .WithMany("CreatedEquipment")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.EquipmentNotificationSubscription", b =>
                {
                    b.HasOne("FailurePredictionSystemBack.Core.Models.Equipment", "Equipment")
                        .WithMany("NotificationSubscriptions")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FailurePredictionSystemBack.Core.Models.User", "User")
                        .WithMany("EquipmentNotificationSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Metric", b =>
                {
                    b.HasOne("FailurePredictionSystemBack.Core.Models.Equipment", "Equipment")
                        .WithMany("Metrics")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Notification", b =>
                {
                    b.HasOne("FailurePredictionSystemBack.Core.Models.Alert", "Alert")
                        .WithMany("Notifications")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FailurePredictionSystemBack.Core.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Prediction", b =>
                {
                    b.HasOne("FailurePredictionSystemBack.Core.Models.Equipment", "Equipment")
                        .WithMany("Predictions")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FailurePredictionSystemBack.Core.Models.Metric", "Metric")
                        .WithOne("Prediction")
                        .HasForeignKey("FailurePredictionSystemBack.Core.Models.Prediction", "MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Alert", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Equipment", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Metrics");

                    b.Navigation("NotificationSubscriptions");

                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Metric", b =>
                {
                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.Prediction", b =>
                {
                    b.Navigation("Alert");
                });

            modelBuilder.Entity("FailurePredictionSystemBack.Core.Models.User", b =>
                {
                    b.Navigation("CreatedEquipment");

                    b.Navigation("EquipmentNotificationSubscriptions");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
